In [1]:
import numpy as np

In [2]:
import numpy as np
print(np.__version__)

1.14.2


#### Differences between Flatten() and Ravel() 

two similar kind of ways to convert a ndarray to 1D array : Flatten() and Ravel()

In [3]:
a = np.array( [ (1,7,3,4),(3,2,4,1) ] )
a

array([[1, 7, 3, 4],
       [3, 2, 4, 1]])

In [4]:
a.flatten()

array([1, 7, 3, 4, 3, 2, 4, 1])

In [5]:
a.ravel()

array([1, 7, 3, 4, 3, 2, 4, 1])

#### why are there two numpy functions to do the same task ?
Differences between Flatten() and Ravel()

__a.ravel():__

(i)  Return only reference/view of original array

(ii) If you modify the array you would notice that the value of original array also changes.

(iii) Ravel is faster than flatten() as it does not occupy any memory.

(iv)  Ravel is a library-level function.

__a.flatten() :__

(i)  Return copy of original array

(ii) If you modify any value of this array value of original array is not affected.

(iii) Flatten() is comparatively slower than ravel() as it occupies memory.

(iv)  Flatten is a method of an ndarray object.

#### ravel()

In [13]:
# Create a numpy array 
a = np.array([(1,2,3,4),(3,1,4,2)]) 

In [14]:
# Let's print the array a 
print ("Original array:\n ")  
print(a) 

Original array:
 
[[1 2 3 4]
 [3 1 4 2]]


In [15]:
# To check the dimension of array (dimension =2) ( and type is numpy.ndarray ) 
print ("Dimension of array-> " , (a.ndim)) 

Dimension of array->  2


In [16]:
print("\nOutput for RAVEL \n")  
# Convert nd array to 1D array 
b = a.ravel() 
  
# Ravel only passes a view of original array to array 'b' 
print(b) 


Output for RAVEL 

[1 2 3 4 3 1 4 2]


In [17]:
b[0]=1000
print(b)

[1000    2    3    4    3    1    4    2]


In [18]:
# Note here that value of original array 'a' at also a[0][0] becomes 1000 
print(a) 

[[1000    2    3    4]
 [   3    1    4    2]]


In [12]:
# Just to check the dimension i.e. 1 (and type is same numpy.ndarray ) 
print ("Dimension of array->" ,(b.ndim)) 

Dimension of array-> 1


#### flatten()

In [13]:
print("\nOutput for FLATTEN \n")  
  
# Convert nd array to 1D array 
c = a.flatten() 
  
# Flatten passes copy of original array to 'c' 
print(c) 
c[0]=0
print(c) 
  
# Note that by changing value of c there is no affect on value of original array 'a' 
print(a) 
  
print ("Dimension of array-> " , (c.ndim)) 


Output for FLATTEN 

[1000    2    3    4    3    1    4    2]
[0 2 3 4 3 1 4 2]
[[1000    2    3    4]
 [   3    1    4    2]]
Dimension of array->  1
